### ISSUE TITLE
unable to build some tools with MonoDevelop

### ISSUE THREAD

**Issue by v1993** [leezer3/OpenBVE#19]
I try to build all OpenBVE develop tools (TrainEditor, RouteViewer and other), but it's impossible.
Object Blender: "Invalid configuration mapping" error in project tree and in build output "Error: /home/v/compile/OpenBVE/ObjectBender/ObjectBender.csproj: /home/v/compile/OpenBVE/ObjectBender/ObjectBender.csproj could not import "$(MSBuildBinPath)\Microsoft.CSharp.Targets" (ObjectBender)"
Object Viewer: "/usr/lib/mono/4.5/Microsoft.Common.targets: Warning: Reference 'OpenBveApi' not resolved (ObjectViewer)" and "/home/v/compile/OpenBVE/ObjectViewer/CSC: Error CS2001: Source file `formOptions.designer.cs' could not be found (CS2001) (ObjectViewer)" in buld output.
Route Vewer: so many errors about "OpenBveApi not resolved".
Train Editor: "Error: /home/v/compile/OpenBVE/TrainEditor/TrainEditor.csproj: /home/v/compile/OpenBVE/TrainEditor/TrainEditor.csproj could not import "$(MSBuildBinPath)\Microsoft.CSharp.targets" (TrainEditor)" in build output.

**Comment by leezer3** [comment]
Hmm, it's tripping up on the fact that you're trying to build on a system with a case-sensitive filesystem
(Mono....)

Monodevelop ought to handle this gracefully, and the fact that it isn't looks like their bug to me, but I think it should be fixable from this end too.

**Comment by leezer3** [comment]
Right, with the two commits above, everything builds correctly on my Ubuntu 15.10 vm.

**Comment by v1993** [comment]
Good, TrainEditor and ObjectBleder build correct, but not viewers. Warning "/usr/lib/mono/4.5/Microsoft.Common.targets: Warning: Reference 'OpenBveApi' not resolved (ObjectViewer)" and many errors about it.

**Comment by leezer3** [comment]
Ah-
You need to have built a copy of OpenBveApi before trying to build the tools...

Need to link the two projects, will sort that.

**Comment by v1993** [comment]
OK, I compile OpenBveApi, now it compiled and run, but it generate errors about "OutOfRange" in OpenTK functions.

**Comment by leezer3** [comment]
The commit above links OpenBveApi to both projects, and they now build correctly with no changes from a fresh checkout.

Something still isn't right though, as the Mono built versions aren't launching right.
Object Viewer built from the same source on a Windows box works OK, but Route Viewer isn't working at all......

Getting there!

**Comment by leezer3** [comment]
Ah, we need to copy the OpenTK.dll.config file to the build directory in all cases, otherwise the DLL mappings don't work right.

**Comment by v1993** [comment]
Now I can't build only RouteViewer: it say "openal32.dll not found".

**Comment by leezer3** [comment]
OK, that's irritating-
It's copying the .dll.config file under Windows, but not under Mono.....

Drop a copy of OpenTK.dll.config (Found in the Dependancies folder) into the Route Viewer binary folder, and it should then work.
Investigating again, but I suspect a casing issue.....

**Comment by leezer3** [comment]
You may also require a copy of the Compatibility folder from the main OpenBVE download (This contains the default Japanese signal and catenery objects) if it crashes when loading a route.

I'll dig into that when the main program launches without troubles from a default build....
